# Generated by Django 4.1.7 on 2023-02-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
